package com.trozovka.wxlite.data

import org.junit.Assert.assertEquals
import org.junit.Assert.assertNull
import org.junit.Test

/**
 * Every expected value here was generated by actually running the Python
 * backend's tiles.py (not hand-computed), specifically including negative
 * longitudes and the +/-180 wraparound — the cases where Python's floored
 * modulo and Kotlin's truncated modulo disagree if not handled explicitly.
 */
class TilesTest {

    @Test
    fun `matches Python tiles_py exactly for real-world ports`() {
        assertEquals("lat0_lon120", Tiles.tileForPosition(14.6, 121.0)) // Manila
        assertEquals("lat0_lon60", Tiles.tileForPosition(1.35, 103.8)) // Singapore
        assertEquals("lat30_lon-60", Tiles.tileForPosition(30.0, -40.0)) // mid-Atlantic
        assertEquals("lat-60_lon120", Tiles.tileForPosition(-33.9, 151.2)) // Sydney
        assertEquals("lat30_lon-60", Tiles.tileForPosition(51.5, -0.1)) // London
    }

    @Test
    fun `matches Python for boundary and origin cases`() {
        assertEquals("lat0_lon0", Tiles.tileForPosition(0.0, 0.0))
        assertEquals("lat-60_lon-180", Tiles.tileForPosition(-60.0, -180.0))
        assertEquals("lat30_lon120", Tiles.tileForPosition(59.99, 179.99))
    }

    @Test
    fun `returns null outside the covered latitude range, matching Python`() {
        assertNull(Tiles.tileForPosition(60.0, 0.0)) // upper bound excluded
        assertNull(Tiles.tileForPosition(-60.01, 0.0)) // just below lower bound
    }

    @Test
    fun `wraps longitude past plus-minus-180 exactly like Python`() {
        assertEquals("lat0_lon120", Tiles.tileForPosition(10.0, -190.0))
        assertEquals("lat0_lon-180", Tiles.tileForPosition(10.0, 190.0))
        assertEquals("lat0_lon-180", Tiles.tileForPosition(10.0, -180.0))
        assertEquals("lat0_lon-180", Tiles.tileForPosition(10.0, 180.0))
        assertEquals("lat-60_lon-180", Tiles.tileForPosition(-45.0, -179.5))
    }

    @Test
    fun `allTileIds matches Python's all_tiles exactly, same order, all 24 tiles`() {
        // Generated by actually running backend/tiles.py's all_tiles(), not
        // hand-computed.
        val expected = listOf(
            "lat-60_lon-180", "lat-60_lon-120", "lat-60_lon-60", "lat-60_lon0", "lat-60_lon60", "lat-60_lon120",
            "lat-30_lon-180", "lat-30_lon-120", "lat-30_lon-60", "lat-30_lon0", "lat-30_lon60", "lat-30_lon120",
            "lat0_lon-180", "lat0_lon-120", "lat0_lon-60", "lat0_lon0", "lat0_lon60", "lat0_lon120",
            "lat30_lon-180", "lat30_lon-120", "lat30_lon-60", "lat30_lon0", "lat30_lon60", "lat30_lon120",
        )
        assertEquals(expected, Tiles.allTileIds())
    }
}
