package com.trozovka.wxlite.data

import org.junit.Assert.assertEquals
import org.junit.Assert.assertNull
import org.junit.Test

/**
 * Every expected value here was generated by actually running the Python
 * backend's tiles.py (not hand-computed), specifically including negative
 * longitudes and the +/-180 wraparound — the cases where Python's floored
 * modulo and Kotlin's truncated modulo disagree if not handled explicitly.
 */
class TilesTest {

    @Test
    fun `matches Python tiles_py exactly for real-world ports`() {
        assertEquals("lat0_lon120", Tiles.tileForPosition(14.6, 121.0)) // Manila
        assertEquals("lat0_lon60", Tiles.tileForPosition(1.35, 103.8)) // Singapore
        assertEquals("lat30_lon-60", Tiles.tileForPosition(30.0, -40.0)) // mid-Atlantic
        assertEquals("lat-60_lon120", Tiles.tileForPosition(-33.9, 151.2)) // Sydney
        assertEquals("lat30_lon-60", Tiles.tileForPosition(51.5, -0.1)) // London
    }

    @Test
    fun `matches Python for boundary and origin cases`() {
        assertEquals("lat0_lon0", Tiles.tileForPosition(0.0, 0.0))
        assertEquals("lat-60_lon-180", Tiles.tileForPosition(-60.0, -180.0))
        assertEquals("lat30_lon120", Tiles.tileForPosition(59.99, 179.99))
    }

    @Test
    fun `returns null outside the covered latitude range, matching Python`() {
        assertNull(Tiles.tileForPosition(60.0, 0.0)) // upper bound excluded
        assertNull(Tiles.tileForPosition(-60.01, 0.0)) // just below lower bound
    }

    @Test
    fun `wraps longitude past plus-minus-180 exactly like Python`() {
        assertEquals("lat0_lon120", Tiles.tileForPosition(10.0, -190.0))
        assertEquals("lat0_lon-180", Tiles.tileForPosition(10.0, 190.0))
        assertEquals("lat0_lon-180", Tiles.tileForPosition(10.0, -180.0))
        assertEquals("lat0_lon-180", Tiles.tileForPosition(10.0, 180.0))
        assertEquals("lat-60_lon-180", Tiles.tileForPosition(-45.0, -179.5))
    }

    @Test
    fun `tilesIntersecting returns just one tile for a box fully inside it`() {
        // A small passage-plan area entirely within the Manila tile
        // (lat0_lon120 spans lat 0-30, lon 120-180) -- kept clear of both
        // boundaries so it can't accidentally straddle a neighboring tile.
        val tiles = Tiles.tilesIntersecting(latMin = 10.0, latMax = 15.0, lonMin = 125.0, lonMax = 130.0)
        assertEquals(listOf("lat0_lon120"), tiles)
    }

    @Test
    fun `tilesIntersecting returns every tile a wider box touches, in grid order`() {
        // A box straddling the lat0/lat30 boundary and the lon60/lon120
        // boundary should pick up all four surrounding tiles.
        val tiles = Tiles.tilesIntersecting(latMin = 25.0, latMax = 35.0, lonMin = 115.0, lonMax = 125.0)
        assertEquals(listOf("lat0_lon60", "lat0_lon120", "lat30_lon60", "lat30_lon120"), tiles)
    }

    @Test
    fun `tilesIntersecting returns nothing for a box entirely outside the covered latitude range`() {
        val tiles = Tiles.tilesIntersecting(latMin = 70.0, latMax = 80.0, lonMin = 0.0, lonMax = 10.0)
        assertEquals(emptyList<String>(), tiles)
    }
}
