package com.trozovka.wxlite.data

import org.junit.Assert.assertEquals
import org.junit.Test

class WxlFileTest {

    /**
     * These exact bytes were generated by the Python backend's own struct
     * format (not just "written to match" — the hex came from actually
     * running `struct.pack` with the real header/point formats), so this
     * test proves the Kotlin parser is byte-for-byte compatible with what
     * pack.py actually produces, not just internally self-consistent.
     */
    private val knownGoodHex =
        "57584c3100002041000030410000f0420000f24202000200a09e6f" +
            "6a94271903fe4826fbf60a0a281e00000b25ec0ff1"

    private fun hexToBytes(hex: String): ByteArray =
        ByteArray(hex.length / 2) { i ->
            hex.substring(i * 2, i * 2 + 2).toInt(16).toByte()
        }

    @Test
    fun `parses header fields correctly`() {
        val file = WxlFile.parse(hexToBytes(knownGoodHex))
        assertEquals(10.0f, file.latMin, 0.001f)
        assertEquals(11.0f, file.latMax, 0.001f)
        assertEquals(120.0f, file.lonMin, 0.001f)
        assertEquals(121.0f, file.lonMax, 0.001f)
        assertEquals(2, file.nLat)
        assertEquals(2, file.nLon)
        assertEquals(1785700000L, file.validTimeSeconds)
        assertEquals(4, file.points.size)
    }

    @Test
    fun `parses grid points correctly, including negative values`() {
        val file = WxlFile.parse(hexToBytes(knownGoodHex))

        val p0 = file.pointAt(0, 0)
        assertEquals(1013.2f, p0.pressureHpa, 0.01f)
        assertEquals(25, p0.tempC)
        assertEquals(3, p0.windU)
        assertEquals(-2, p0.windV)

        val p1 = file.pointAt(0, 1)
        assertEquals(980.0f, p1.pressureHpa, 0.01f)
        assertEquals(-5, p1.tempC)
        assertEquals(-10, p1.windU)
        assertEquals(10, p1.windV)

        val p3 = file.pointAt(1, 1)
        assertEquals(948.3f, p3.pressureHpa, 0.01f)
        assertEquals(-20, p3.tempC)
        assertEquals(15, p3.windU)
        assertEquals(-15, p3.windV)
    }

    @Test(expected = IllegalArgumentException::class)
    fun `rejects a file with the wrong magic bytes`() {
        val bad = hexToBytes(knownGoodHex)
        bad[0] = 'X'.code.toByte()
        WxlFile.parse(bad)
    }
}
