package com.trozovka.wxlite.map

import org.junit.Assert.assertEquals
import org.junit.Test

class CoastlineDataTest {

    /** Generated by actually running backend/pack_coastline.py's own
     * struct format against known coordinates, not hand-encoded. */
    private val knownGoodHex =
        "434f5354020000000300b405442fdc05762f8c05942f0200e6fb1d29b4fb6829"

    private fun hexToBytes(hex: String): ByteArray =
        ByteArray(hex.length / 2) { i -> hex.substring(i * 2, i * 2 + 2).toInt(16).toByte() }

    @Test
    fun `parses two polygons with correct point counts`() {
        val polygons = CoastlineData.parse(hexToBytes(knownGoodHex))
        assertEquals(2, polygons.size)
        assertEquals(3, polygons[0].points.size)
        assertEquals(2, polygons[1].points.size)
    }

    @Test
    fun `parses coordinates correctly, including negative values`() {
        val polygons = CoastlineData.parse(hexToBytes(knownGoodHex))

        val p0 = polygons[0].points[0]
        assertEquals(14.6, p0.lat, 0.001)
        assertEquals(121.0, p0.lon, 0.001)

        val p1 = polygons[0].points[2]
        assertEquals(14.2, p1.lat, 0.001)
        assertEquals(121.8, p1.lon, 0.001)

        val negative = polygons[1].points[0]
        assertEquals(-10.5, negative.lat, 0.001)
        assertEquals(105.25, negative.lon, 0.001)
    }

    @Test(expected = IllegalArgumentException::class)
    fun `rejects wrong magic bytes`() {
        val bad = hexToBytes(knownGoodHex)
        bad[0] = 'X'.code.toByte()
        CoastlineData.parse(bad)
    }
}
